# Generated by Django 3.1.5 on 2021-05-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.message', verbose_name='Сообщение'),
        ),
    ]
