# Generated by Django 3.1.5 on 2021-05-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20210520_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.profile', verbose_name='Отправитель'),
        ),
    ]
