# Generated by Django 3.1.5 on 2021-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0006_auto_20210526_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='token',
            field=models.ManyToManyField(null=True, to='chatroom.Token', verbose_name='Токен'),
        ),
    ]
