# Generated by Django 3.1.5 on 2021-05-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0007_auto_20210526_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatroom.chat', verbose_name='Чат'),
        ),
    ]
