# Generated by Django 3.1.5 on 2021-05-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0010_auto_20210526_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='chatroom.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.CharField(max_length=256, verbose_name='Публичный ключ'),
        ),
    ]
