# Generated by Django 3.1.5 on 2021-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0011_auto_20210526_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего сообщения'),
        ),
    ]
