# Generated by Django 3.1.5 on 2021-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0013_auto_20210526_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='g',
            field=models.CharField(max_length=256, null=True, verbose_name='Число для степени'),
        ),
        migrations.AddField(
            model_name='chat',
            name='p',
            field=models.CharField(max_length=256, null=True, verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='chat',
            name='public_key_user1',
            field=models.CharField(max_length=256, null=True, verbose_name='Публичное число для первого пользователя'),
        ),
        migrations.AddField(
            model_name='chat',
            name='public_key_user2',
            field=models.CharField(max_length=256, null=True, verbose_name='Публичное число для второго пользователя'),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('1', 'Запрос на создание'), ('2', 'Второй пользователь принял'), ('3', 'Успешно создан')], max_length=256, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(max_length=256, null=True, verbose_name='Сессия'),
        ),
    ]
