# Generated by Django 3.1.5 on 2021-05-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0014_auto_20210527_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_create_chat', to='chatroom.profile', verbose_name='Создатель чата'),
        ),
    ]
