# Generated by Django 3.1.5 on 2021-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0015_chat_create_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='token',
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(null=True, to='chatroom.Profile', verbose_name='Пользователи'),
        ),
    ]
