# Generated by Django 3.1.5 on 2021-05-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0016_auto_20210527_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('1', 'Чат создан'), ('2', 'Первый пользователь отправил приглашение'), ('3', 'Второй пользователь принял'), ('4', 'Успешно создан')], max_length=256, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatroom.profile', verbose_name='Пользователь токена'),
        ),
    ]
