# Generated by Django 2.2.24 on 2021-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0017_auto_20210527_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='g',
            field=models.CharField(max_length=10, null=True, verbose_name='Число для степени'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='chates', to='chatroom.Profile', verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_access',
            field=models.CharField(max_length=256, null=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=512, verbose_name='Токен'),
        ),
    ]
